### ISSUE TITLE
Linux port?

### ISSUE THREAD

**Issue by q4a** [n1f7/FarCry#1]
Привет. Ты случайно не планировал делать Linux порт?
А то мы тут уже немного пытаемся:
https://github.com/q4a/farcry - я прикрутил сборку x86/x64 в cmake.
https://github.com/Footsiefat/FarCry/tree/cmake_port - еще 1 уже пробует собирать в Linux, но пока в старой ветке.
Если есть дискорд, то можешь добавиться: https://discord.com/invite/far-cry-1-community-472740869208801292

**Comment by r-a-sattarov** [comment]
Hi! Here is the fork that started porting the game to Linux - https://github.com/rohit-n/FarCry
